language: python
os: linux
dist: bionic
python:
  - "3.10"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - mkdir ./tools
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./tools

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

# command to run tests
script:
  # - pytest
  - black --check .
  - flake8 --max-line-length=88
  - coverage run --source=mysite,polls manage.py test
  - coverage xml
  - ./tools/coveralls report --repo-token=$COVERALLS_REPO_TOKEN ./coverage.xml

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "$AWS_REGION"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "$AWS_BUCKET"
  on:
      branch: main
